### ISSUE TITLE
live caption does not work

### ISSUE THREAD

**Issue by everconnectcn** [justclueless/chromium-win64#5]
Hello, I've tried out this version, [v104.0.5084.0-r0-AVX2](https://github.com/justclueless/chromium-win64/releases/tag/v104.0.5084.0-r0-AVX2). I found out that the live caption does not work? Can you fix it? Or can you elaborate on why it does not work and maybe I can fix it myself?

**Comment by justclueless** [comment]
@everconnectcn I don't know, I don't use that functionality so never noticed it being there or working or not working. 
Was it working on my previous builds?
My builds are "nosync" builds, so no google translate, sync settings to cloud...etc. So if that's required, then that's probs why it doesn't work. 

Upon trying myself, it looks like it downloaded some stuff and clicking on settings opens my Windows Settings window for captioning. So if this is OS dependent, then I dunno, there's too many variables and too many things that could've caused it to not work. 

In either case, since it's a functionality that I don't use, I'm not particularly concerned with it. If it's a chromium revision thing and it comes back next time I build, then cool, if not, then I guess my builds don't have "live caption" functionality. 

For now, I don't have the knowledge of how it works, or anything about it, so I can't direct you on how to solve this issue, or solve it myself.

**Comment by justclueless** [comment]
This is looking like an upstream issue, so I'm closing this for now

**Comment by everconnectcn** [comment]
OK, thank you so much for your explanation
